WARNING django.request Not Found: /favicon.ico 2021-08-14 22:04:37,048
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2021-08-14 22:04:37,050
ERROR django.request Internal Server Error: /work/excel/ 2021-08-14 22:04:55,181
Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\Projects\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\user\OneDrive\Desktop\Projects\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "C:\Users\user\OneDrive\Desktop\Projects\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 309, in check_response
    raise ValueError(
ValueError: The view work.views.generate_case_excel didn't return an HttpResponse object. It returned None instead.
ERROR django.server "GET /work/excel/ HTTP/1.1" 500 68439 2021-08-14 22:04:55,184
WARNING django.request Not Found: /favicon.ico 2021-08-14 22:05:36,505
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2021-08-14 22:05:36,506
