WARNING django.request Not Found: /favicon.ico 2022-05-10 08:06:16,028
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:06:16,029
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:06:26,189
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:06:26,189
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:34:07,624
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:34:07,625
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:34:08,354
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:34:08,355
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:34:08,679
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:34:08,680
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:34:08,903
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:34:08,904
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:34:09,096
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:34:09,097
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:34:09,290
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:34:09,290
ERROR django.request Internal Server Error: /analytic/migrant-detail/46/ 2022-05-10 08:34:18,104
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\databases_v1\statistica\views.py", line 198, in case_migrant_detail
    return render(request, 'statistica/detail_migrant.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 994, in render
    return render_value_in_context(output, context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 973, in render_value_in_context
    value = str(value)
TypeError: __str__ returned non-string (type NoneType)
ERROR django.server "GET /analytic/migrant-detail/46/ HTTP/1.1" 500 142371 2022-05-10 08:34:18,110
ERROR django.request Internal Server Error: /analytic/migrant-detail/46/ 2022-05-10 08:36:17,786
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\databases_v1\statistica\views.py", line 198, in case_migrant_detail
    return render(request, 'statistica/detail_migrant.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 994, in render
    return render_value_in_context(output, context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 973, in render_value_in_context
    value = str(value)
TypeError: __str__ returned non-string (type NoneType)
ERROR django.server "GET /analytic/migrant-detail/46/ HTTP/1.1" 500 142508 2022-05-10 08:36:17,790
ERROR django.request Internal Server Error: /analytic/migrant-detail/46/ 2022-05-10 08:36:18,666
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\databases_v1\statistica\views.py", line 198, in case_migrant_detail
    return render(request, 'statistica/detail_migrant.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 994, in render
    return render_value_in_context(output, context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 973, in render_value_in_context
    value = str(value)
TypeError: __str__ returned non-string (type NoneType)
ERROR django.server "GET /analytic/migrant-detail/46/ HTTP/1.1" 500 142508 2022-05-10 08:36:18,673
ERROR django.request Internal Server Error: /analytic/migrant-detail/52/ 2022-05-10 08:36:34,393
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\databases_v1\statistica\views.py", line 198, in case_migrant_detail
    return render(request, 'statistica/detail_migrant.html', locals())
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\test\utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 994, in render
    return render_value_in_context(output, context)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\template\base.py", line 973, in render_value_in_context
    value = str(value)
TypeError: __str__ returned non-string (type NoneType)
ERROR django.server "GET /analytic/migrant-detail/52/ HTTP/1.1" 500 143060 2022-05-10 08:36:34,397
ERROR django.request Internal Server Error: /analytic/migrant-detail/46/ 2022-05-10 08:38:35,239
Traceback (most recent call last):
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Users\ntabyldieva\Desktop\crm\databases_v1\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Users\ntabyldieva\Desktop\databases_v1\statistica\views.py", line 194, in case_migrant_detail
    print(case.entrepreneur)
TypeError: __str__ returned non-string (type NoneType)
ERROR django.server "GET /analytic/migrant-detail/46/ HTTP/1.1" 500 68578 2022-05-10 08:38:35,241
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:39:23,383
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:39:23,384
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:39:24,431
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:39:24,432
WARNING django.request Not Found: /favicon.ico 2022-05-10 08:40:24,210
WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3524 2022-05-10 08:40:24,211
